backend/todo/urls.py
from django.urls import include, path
from rest_framework import routers

from backend.todo import views as v
from backend.todo.api.viewsets import TodoViewSet

app_name = 'todo'

router = routers.DefaultRouter()

router.register(r'todos', TodoViewSet)

todo_urlpatterns = [
    path('', v.TodoListView.as_view(), name='todo_list'),
    path('<int:pk>/', v.TodoDetailView.as_view(), name='todo_detail'),
    path('create/', v.TodoCreateView.as_view(), name='todo_create'),
    path('<int:pk>/update/', v.TodoUpdateView.as_view(), name='todo_update'),
    path('<int:pk>/delete/', v.TodoDeleteView.as_view(), name='todo_delete'),
]

urlpatterns = [
    path('todo/', include(todo_urlpatterns)),
    path('api/v1/', include(router.urls)),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('backend.core.urls', namespace='core')),
    path('', include('backend.crm.urls', namespace='crm')),
    path('', include('backend.example.urls', namespace='example')),
    path('', include('backend.hotel.urls', namespace='hotel')),
    path('', include('backend.movie.urls', namespace='movie')),
    path('', include('backend.order.urls', namespace='order')),
    path('', include('backend.school.urls', namespace='school')),
    path('', include('backend.todo.urls', namespace='todo')),
    path('', include('backend.video.urls', namespace='video')),
    path('admin/', admin.site.urls),
]

# djoser
urlpatterns += [
    path('api/v1/', include('djoser.urls')),
    path('api/v1/auth/', include('djoser.urls.authtoken')),
]

# swagger
urlpatterns += [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),  # noqa E501
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),  # noqa E501
]

backend/todo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse_lazy

STATUS = (
    ('p', 'Pendente'),
    ('a', 'Aprovado'),
    ('c', 'Cancelado'),
)


class Todo(models.Model):
    task = models.CharField('tarefa', max_length=50)
    description = models.TextField('descrição', null=True, blank=True)
    is_done = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(
        User,
        on_delete=models.SET_NULL,
        null=True,
        blank=True
    )
    status = models.CharField(max_length=1, choices=STATUS, default='p')

    def __str__(self):
        return f"{self.task}"

    class Meta:
        verbose_name = "Tarefa"
        verbose_name_plural = "Tarefas"

    def get_absolute_url(self):
        return reverse_lazy('todo:todo_detail', kwargs={'pk': self.pk})

backend/todo/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Todo


class TodoForm(forms.ModelForm):
    required_css_class = 'required'

    class Meta:
        model = Todo
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(TodoForm, self).__init__(*args, **kwargs)

        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

        # Remove a class de is_done.
        self.fields['is_done'].widget.attrs['class'] = None

        # Torna description somente leitura.
        self.fields['description'].widget.attrs['readonly'] = True

    # def clean(self):
    #     self.cleaned_data = super().clean()
    #     self.description = self.cleaned_data.get('description')
    #     self.label = self.fields['description'].label

    #     if self.description or (self.instance.pk and self.description != self.instance.description):
    #         raise ValidationError(f'O campo {self.label} não pode ser editado.')

    #     return self.cleaned_data

    def clean_description(self):
        self.description = self.cleaned_data.get('description')
        self.label = self.fields['description'].label

        if self.description or (self.instance.pk and self.description != self.instance.description):
            raise ValidationError(f'O campo {self.label} não pode ser editado.')

        return self.cleaned_data['description']

backend/todo/views.py
from django.urls import reverse_lazy
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    ListView,
    UpdateView
)

from .forms import TodoForm
from .models import Todo


class TodoListView(ListView):
    model = Todo
    paginate_by = 10


class TodoDetailView(DetailView):
    model = Todo


class TodoCreateView(CreateView):
    model = Todo
    form_class = TodoForm


class TodoUpdateView(UpdateView):
    model = Todo
    form_class = TodoForm


class TodoDeleteView(DeleteView):
    model = Todo
    success_url = reverse_lazy('todo:todo_list')

backend/todo/templates/todo/todo_confirm_delete.html
<!-- todo_confirm_delete.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Deletar</h1>
  <div class="cols-6">
    <form action="." method="POST">
      <div class="col-sm-6">
        {% csrf_token %}
        <p>Deseja deletar {{ object }} ?</p>
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Sim</button>
          <a class="btn btn-danger" href="{% url 'todo:todo_list' %}">Não</a>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

backend/todo/templates/todo/todo_detail.html
<!-- todo_detail.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Detalhes</h1>

  <ul>
    <li><b>Tarefa:</b> {{ object.task }}</li>
    <li><b>Descrição:</b> {{ object.description }} </li>
    <li><b>Feito?</b>
      {% if object.is_done %}
        <i class="fa fa-check-circle ok"></i>
      {% else %}
        <i class="fa fa-times-circle no"></i>
      {% endif %}
    </li>
    <li><b>Criado em:</b> {{ object.created|date:'d/m/Y'|default:'---' }}</li>
  </ul>
{% endblock content %}

backend/todo/templates/todo/todo_form.html
<!-- todo_form.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Tarefa</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

backend/todo/templates/todo/todo_list.html
<!-- todo_list.html -->
{% extends "base.html" %}

{% block content %}
  <h1>
    Lista
    <a class="btn btn-primary" href="{% url 'todo:todo_create' %}">Adicionar</a>
  </h1>
  <table class="table">
    <thead>
      <tr>
        <th>Tarefa</th>
        <th>Descrição</th>
        <th>Feito?</th>
        <th>Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for object in object_list %}
        <tr>
          <td>
            <a href="{{ object.get_absolute_url }}">{{ object.task }}</a>
          </td>
          <td>{{ object.description }}</td>
          <td>
            {% if object.is_done %}
              <i class="fa fa-check-circle ok"></i>
            {% else %}
              <i class="fa fa-times-circle no"></i>
            {% endif %}
          </td>
          <td>
            <a href="{% url 'todo:todo_update' object.pk %}">
              <i class="fa fa-edit"></i>
            </a>
            <a href="{% url 'todo:todo_delete' object.pk %}" style="padding-left: 7px">
              <i class="fa fa-close no"></i>
            </a>
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  {% include "includes/pagination.html" %}
{% endblock content %}