backend/core/urls.py
from django.urls import path

from .views import index

app_name = 'core'

urlpatterns = [
    path('', index, name='index'),
]

backend/order/urls.py
from django.urls import path

from backend.order import views as v

app_name = 'order'


urlpatterns = [
    path('order/', v.order_list, name='order_list'),
    path('order/create/', v.order_create, name='order_create'),
]

backend/todo/urls.py
from django.urls import include, path
from rest_framework import routers

from backend.todo import views as v
from backend.todo.api.viewsets import TodoViewSet

app_name = 'todo'

router = routers.DefaultRouter()

router.register(r'todos', TodoViewSet)

todo_urlpatterns = [
    path('', v.TodoListView.as_view(), name='todo_list'),
    path('<int:pk>/', v.TodoDetailView.as_view(), name='todo_detail'),
    path('create/', v.TodoCreateView.as_view(), name='todo_create'),
    path('<int:pk>/update/', v.TodoUpdateView.as_view(), name='todo_update'),
    path('<int:pk>/delete/', v.TodoDeleteView.as_view(), name='todo_delete'),
]

urlpatterns = [
    path('todo/', include(todo_urlpatterns)),
    path('api/v1/', include(router.urls)),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('backend.core.urls', namespace='core')),
    path('', include('backend.crm.urls', namespace='crm')),
    path('', include('backend.example.urls', namespace='example')),
    path('', include('backend.hotel.urls', namespace='hotel')),
    path('', include('backend.movie.urls', namespace='movie')),
    path('', include('backend.order.urls', namespace='order')),
    path('', include('backend.school.urls', namespace='school')),
    path('', include('backend.todo.urls', namespace='todo')),
    path('', include('backend.video.urls', namespace='video')),
    path('admin/', admin.site.urls),
]

# djoser
urlpatterns += [
    path('api/v1/', include('djoser.urls')),
    path('api/v1/auth/', include('djoser.urls.authtoken')),
]

# swagger
urlpatterns += [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),  # noqa E501
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),  # noqa E501
]

backend/video/urls.py
from django.urls import include, path

from backend.video import views as v

app_name = 'video'

v1_urlpatterns = [
    path('videos/', v.videos, name='videos'),
    path('videos/<int:pk>/', v.video, name='video'),
]

urlpatterns = [
    path('api/v1/', include(v1_urlpatterns)),
]

backend/core/models.py
from django.db import models

# Create your models here.

backend/core/views.py
from django.shortcuts import render


def index(request):
    template_name = 'index.html'
    return render(request, template_name)

backend/core/templates/includes/nav.html
<!-- includes/nav.html -->
<!-- https://getbootstrap.com/docs/4.0/examples/starter-template/ -->
<!-- https://github.com/JTruax/bootstrap-starter-template/blob/master/template/start.html -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="{% url 'core:index' %}">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'core:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'todo:todo_list' %}">Tarefas</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'order:order_list' %}">Pedidos</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/api/v1/todos/">API V1</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'video:videos' %}">API V1 Video (Django puro)</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/swagger/">Swagger</a>
      </li>
    </ul>
  </div>
</nav>

backend/core/templates/includes/pagination.html
<!-- pagination.html -->
{% load url_replace %}
<!-- https://gist.github.com/rg3915/01ca76f099f431c24bc0536bef83076b -->
<!-- Use https://gist.github.com/rg3915/01ca76f099f431c24bc0536bef83076b#file-pagination02-html -->
<div class="row text-center">
  <div class="col-lg-12">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.previous_page_number %}">&laquo;</a></li>
      {% endif %}

      {% for pg in page_obj.paginator.page_range %}
        <!-- Sempre mostra as 3 primeiras e 3 últimas páginas -->
        {% if pg == 1 or pg == 2 or pg == 3 or pg == page_obj.paginator.num_pages or pg == page_obj.paginator.num_pages|add:'-1' or pg == page_obj.paginator.num_pages|add:'-2' %}
          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?{% url_replace page=pg %}">{{ pg }}</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?{% url_replace page=pg %}">{{ pg }}</a></li>
          {% endif %}

        {% else %}

          {% if page_obj.number == pg %}
            <li class="page-item active"><a class="page-link" href="?{% url_replace page=pg %}">{{ pg }}</a></li>
          {% elif pg > page_obj.number|add:'-4' and pg < page_obj.number|add:'4' %} <!-- Mostra 3 páginas antes e 3 páginas depois da atual -->
            <li class="page-item"><a class="page-link" href="?{% url_replace page=pg %}">{{ pg }}</a></li>
          {% elif pg == page_obj.number|add:'-4' or pg == page_obj.number|add:'4' %}
            <li class="page-item"><a class="page-link" href="">...</a></li>
          {% endif %}
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item"><a class="page-link" href="?{% url_replace page=page_obj.next_page_number %}">&raquo;</a></li>
      {% endif %}
    </ul>
  </div>
</div>