backend/order/urls.py
from django.urls import path

from backend.order import views as v

app_name = 'order'


urlpatterns = [
    path('order/', v.order_list, name='order_list'),
    path('order/create/', v.order_create, name='order_create'),
]

backend/urls.py
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework import permissions

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version='v1',
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('backend.core.urls', namespace='core')),
    path('', include('backend.crm.urls', namespace='crm')),
    path('', include('backend.example.urls', namespace='example')),
    path('', include('backend.hotel.urls', namespace='hotel')),
    path('', include('backend.movie.urls', namespace='movie')),
    path('', include('backend.order.urls', namespace='order')),
    path('', include('backend.school.urls', namespace='school')),
    path('', include('backend.todo.urls', namespace='todo')),
    path('', include('backend.video.urls', namespace='video')),
    path('admin/', admin.site.urls),
]

# djoser
urlpatterns += [
    path('api/v1/', include('djoser.urls')),
    path('api/v1/auth/', include('djoser.urls.authtoken')),
]

# swagger
urlpatterns += [
   path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),  # noqa E501
   path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),  # noqa E501
]

backend/order/models.py
from django.contrib.auth.models import User
from django.db import models


class Department(models.Model):
    name = models.CharField('nome', max_length=255, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'

    def __str__(self):
        return f'{self.name}'


class Employee(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='usuário',
        related_name='user_employees',
    )
    department = models.ForeignKey(
        Department,
        on_delete=models.SET_NULL,
        verbose_name='departamento',
        related_name='department_employees',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('user__first_name',)
        verbose_name = 'Funcionário'
        verbose_name_plural = 'Funcionários'

    @property
    def full_name(self):
        return f'{self.user.first_name} {self.user.last_name or ""}'.strip()

    def __str__(self):
        return self.full_name


class Order(models.Model):
    title = models.CharField('título', max_length=255)
    employee = models.ForeignKey(
        Employee,
        on_delete=models.SET_NULL,
        verbose_name='funcionário',
        related_name='orders',
        null=True,
        blank=True
    )

    class Meta:
        ordering = ('title',)
        verbose_name = 'Pedido'
        verbose_name_plural = 'Pedidos'

    def __str__(self):
        return self.title

backend/order/forms.py
from django import forms

from .models import Employee, Order


class OrderForm(forms.ModelForm):
    required_css_class = 'required'

    employee = forms.ModelChoiceField(
        label='Funcionário',
        queryset=None,
    )

    class Meta:
        model = Order
        fields = '__all__'

    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Retorna o funcionário logado.
        employee = user.user_employees.first()

        # Retorna o departamento do funcionário logado.
        department = employee.department

        # Retorna somente os funcionários do meu departamento.
        employees = Employee.objects.filter(department=department)

        # Altera o filtro de ModelChoiceField.
        self.fields['employee'].queryset = employees

        # Adiciona classe form-control nos campos.
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'

backend/order/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import OrderForm
from .models import Order


def order_list(request):
    template_name = 'order/order_list.html'
    object_list = Order.objects.all()
    context = {'object_list': object_list}
    return render(request, template_name, context)


@login_required
def order_create(request):
    template_name = 'order/order_form.html'
    # Passa o usuário logado no formulário.
    form = OrderForm(request.user, request.POST or None)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect('order:order_list')

    context = {'form': form}
    return render(request, template_name, context)

backend/order/templates/order/order_form.html
<!-- order_form.html -->
{% extends "base.html" %}

{% block content %}
  <h1>Adicionar Pedido</h1>
  <div class="cols-6">
    <form class="form-horizontal" action="." method="POST" enctype="multipart/form-data">
      <div class="col-sm-6">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="form-group">
          <button type="submit" class="btn btn-primary">Salvar</button>
        </div>
      </div>
    </form>
  </div>
{% endblock content %}

backend/order/templates/order/order_list.html
<!-- order_list.html -->
{% extends "base.html" %}

{% block content %}
  <div>
    <div class="row">
      <div class="col-auto">
        <h1>Lista de Pedidos</h1>
      </div>
      <div class="col-auto">
        <a
          class="btn btn-primary"
          href="{% url 'order:order_create' %}"
        >Adicionar</a>
      </div>
    </div>
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Pedido</th>
          <th>Funcionário</th>
        </tr>
      </thead>
      <tbody>
        {% for object in object_list %}
          <tr>
            <td>{{ object.id }}</td>
            <td>{{ object.title }}</td>
            <td>{{ object.employee }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  {% include "includes/pagination.html" %}

{% endblock content %}